# Remove Duplicates Script
# This script reads a CSV file generated by Find-DuplicateNames.ps1 and removes duplicate files
# 
# Usage:
#   .\Remove-Duplicates.ps1 -CsvPath "DuplicateNames_5.csv" -WhatIf
#   .\Remove-Duplicates.ps1 -CsvPath "DuplicateNames_5.csv"  # Actually delete files
#
# Parameters:
#   -CsvPath: Path to the CSV file containing duplicate files
#   -WhatIf: Show what would be deleted without actually deleting
#   -Confirm: Ask for confirmation before each deletion

param(
    [Parameter(Mandatory=$true)]
    [string]$CsvPath,
    
    [switch]$WhatIf,
    
    [switch]$Confirm
)

# Validate CSV file exists
if (-not (Test-Path $CsvPath)) {
    Write-Host "Error: CSV file not found: $CsvPath" -ForegroundColor Red
    exit 1
}

Write-Host "Remove Duplicates Tool" -ForegroundColor Cyan
Write-Host "======================" -ForegroundColor Cyan
Write-Host ""

# Load CSV data
Write-Host "Loading CSV file..." -ForegroundColor Yellow
$duplicates = Import-Csv -Path $CsvPath

if ($duplicates.Count -eq 0) {
    Write-Host "No duplicates found in CSV file." -ForegroundColor Green
    exit 0
}

Write-Host "Found $($duplicates.Count) duplicate file(s) in the CSV." -ForegroundColor White
Write-Host ""

# Calculate total space to be freed
$totalSpaceBytes = ($duplicates | Measure-Object -Property SizeBytes -Sum).Sum
$totalSpaceMB = [math]::Round($totalSpaceBytes / 1MB, 2)
$totalSpaceGB = [math]::Round($totalSpaceBytes / 1GB, 2)

if ($totalSpaceGB -ge 1) {
    Write-Host "Total disk space to be freed: $totalSpaceGB GB" -ForegroundColor Yellow
} else {
    Write-Host "Total disk space to be freed: $totalSpaceMB MB" -ForegroundColor Yellow
}
Write-Host ""

# Show operation mode
if ($WhatIf) {
    Write-Host "Running in SIMULATION mode (-WhatIf). No files will be deleted." -ForegroundColor Cyan
} elseif ($Confirm) {
    Write-Host "Running in CONFIRMATION mode. You will be asked to confirm each deletion." -ForegroundColor Yellow
} else {
    Write-Host "WARNING: Running in DELETION mode. Files will be permanently deleted!" -ForegroundColor Red
    $confirmation = Read-Host "Are you sure you want to continue? (type 'YES' to confirm)"
    if ($confirmation -ne 'YES') {
        Write-Host "Operation cancelled." -ForegroundColor Yellow
        exit 0
    }
}
Write-Host ""

# Process deletions
$successCount = 0
$failCount = 0
$skippedCount = 0
$freedSpace = 0

Write-Host "Processing files..." -ForegroundColor Yellow
Write-Host ""

$totalFiles = $duplicates.Count
$currentFile = 0

foreach ($duplicate in $duplicates) {
    $currentFile++
    $percent = [math]::Round(($currentFile / $totalFiles) * 100)
    Write-Progress -Activity "Removing duplicates" -Status "Processing $currentFile of $totalFiles" -PercentComplete $percent
    
    $filePath = $duplicate.FullPath
    $fileName = $duplicate.FileName
    $sizeBytes = [long]$duplicate.SizeBytes
    
    # Check if file exists
    if (-not (Test-Path $filePath)) {
        Write-Host "SKIP: File not found - $filePath" -ForegroundColor Gray
        $skippedCount++
        continue
    }
    
    # Handle confirmation mode
    if ($Confirm -and -not $WhatIf) {
        $response = Read-Host "Delete '$filePath' ($($duplicate.SizeMB) MB)? (Y/N)"
        if ($response -ne 'Y' -and $response -ne 'y') {
            Write-Host "SKIP: User skipped - $filePath" -ForegroundColor Gray
            $skippedCount++
            continue
        }
    }
    
    # Delete file
    try {
        if ($WhatIf) {
            Write-Host "WOULD DELETE: $filePath ($($duplicate.SizeMB) MB)" -ForegroundColor Cyan
        } else {
            Remove-Item -Path $filePath -Force -ErrorAction Stop
            Write-Host "DELETED: $filePath ($($duplicate.SizeMB) MB)" -ForegroundColor Green
        }
        $successCount++
        $freedSpace += $sizeBytes
    }
    catch {
        Write-Host "FAILED: $filePath - $($_.Exception.Message)" -ForegroundColor Red
        $failCount++
    }
}

Write-Progress -Activity "Removing duplicates" -Completed

# Summary
Write-Host ""
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "DELETION SUMMARY" -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan

if ($WhatIf) {
    Write-Host "Files that would be deleted: $successCount" -ForegroundColor White
} else {
    Write-Host "Files successfully deleted: $successCount" -ForegroundColor Green
    Write-Host "Files failed to delete: $failCount" -ForegroundColor Red
}
Write-Host "Files skipped: $skippedCount" -ForegroundColor Gray

$freedSpaceMB = [math]::Round($freedSpace / 1MB, 2)
$freedSpaceGB = [math]::Round($freedSpace / 1GB, 2)

if ($WhatIf) {
    if ($freedSpaceGB -ge 1) {
        Write-Host "Disk space that would be freed: $freedSpaceGB GB" -ForegroundColor Yellow
    } else {
        Write-Host "Disk space that would be freed: $freedSpaceMB MB" -ForegroundColor Yellow
    }
} else {
    if ($freedSpaceGB -ge 1) {
        Write-Host "Disk space freed: $freedSpaceGB GB" -ForegroundColor Green
    } else {
        Write-Host "Disk space freed: $freedSpaceMB MB" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "Operation complete!" -ForegroundColor Green
